# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/modules/core/misc/java/src/java/core+Core.jcode.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/modules/java/common.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/modules/java/generator/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/modules/java/generator/android/java/org/opencv/android/OpenCVLoader.java.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/modules/java/generator/src/java/org/opencv/osgi/OpenCVNativeLoader.java.in))

/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/BuildXcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.14.0/bin/cmake -H/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6 -B/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/BuildXcode
