# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/apps/annotation/CMakeLists.txt))

/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/BuildXcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.14.0/bin/cmake -H/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6 -B/Users/mac/Documents/GitHub/MacLearn/Source/opencv-3.4.6/BuildXcode
